config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href= rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Nunito" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "shuriken.png" %>
      <% end %>
    </div>

    <ul>
      <li id="website" class="category">Website</li>
      <li><%=  link_to "Blog", root_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/uprompti">Twitter</a></li>
      <li><a href="https://www.linkedin.com/in/joannajoseph/">LinkedIn</a></li>
      <li><a href="https://github.com/elainefirefly">GitHub</a></li>
      <li><a href="https://www.facebook.com/uprompti">facebook</a></li>
    </ul>
    <p class="sign_in">Admin Login</p>
  </div>

  <div id="main_content">
    <div id="header">
      <p><%= link_to "All Posts", posts_path %></p>
      <div class="buttons">
        <button class="button"><%= link_to "New Post", new_post_path %></button>
        <button class="button">Log Out</button>
      </div>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
    <%= yield %>
  </div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime('%B %d, %Y') %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>
    <%= form_for :post, url: posts_path do |f| %>
      <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
      </p>

      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %><br>
      </p>

      <p>
        <%= f.submit %>
      </p>
    <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>
</div>